In [5]:
from helpers import reader

In [11]:
mc = False
r = reader.Reader(mc=mc)
r.read_results()
df_results = r.df

In [13]:
df_results
min_df_grouped = df_results[['N','min_energy',"N_dim"]].groupby('N').min().reset_index()
#min_df_grouped['N_dim'] = min_df_grouped['N'].apply(bin).apply(len)-2
min_df_grouped = min_df_grouped[['N_dim','min_energy']]
me_df = min_df_grouped.copy()
me_df['N_dim'] = min_df_grouped['N_dim'].astype('category')
me_df = me_df[me_df['min_energy']==0].groupby('N_dim').size().to_frame('count')#.reset_index(name='count')
total_df = min_df_grouped.groupby('N_dim').count().rename(columns={'min_energy':'total'})
result_df = me_df.copy()
result_df['mmt'] = me_df['count'] / total_df['total'] *100

if mc:
    filename = 'mc.pckl'
else:
    filename = 'mmt.pckl'
with open(f'/home/atg205/Documents/clone-multiplier-encoder-5/p/dfs/grd_states/{filename}','wb') as f:
    result_df.to_pickle(f)

result_df

/tmp/ipykernel_6204/2590544890.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  me_df = me_df[me_df['min_energy']==0].groupby('N_dim').size().to_frame('count')#.reset_index(name='count')

       count    mmt
N_dim
4          2  100.0
5          9  100.0
6          7  100.0
7          7  100.0
8          7  100.0
9         12  100.0
10         6   60.0
11         1   12.5
12         0    0.0
13         0    0.0
14         0    0.0
15         0    0.0
16         0    0.0
17         0    0.0
18         0    0.0
19         0    0.0